### ISSUE TITLE
Checklist of Fixes and Updates before version 1.0 release

### ISSUE THREAD

**Issue by tnylea** [thedevdojo/voyager#1448]
Feel free to add your own checklist similar to this. I am creating this issue to show a check list of things I will be working on before getting the version 1.0 release out the door.

- [x] Fix the *font reference* link, currently it is broken in the latest version
- [x] In the Media Manager moving a file is currently broken, fix it.
- [x] Remove the Anchor button from sidebar toggle. If user toggles it open, keep it open in the next page load, if it is not toggled, then it will remain closed on the next page load.
- [x] If storage is not local, hide the symlink warning in the dashboard
- [x] Possibly Add a new Menu Item under tools called Compass, this will show a link to Voyager resources like the font reference, documentation, cheatsheet, and a few other resources.
- [x] Possibly add a new Menu Item under tools called LogBook, that displays the laravel log file in a nice way.
- [x] Fix issue where sidebar dropdown menu is not working on the Media page.

**Comment by lancepioch** [comment]
Labels: testing, refactor

Close (congrats for 1.0 release 👍 )
