### ISSUE TITLE
Tests and stability

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#990]
In order to get stability for this project, I am now going to make a set of tests to test different scenarios. I am gonna keep this open for everyone to contribute with their tests or ideas.
My main goal is to ensure a certain quality for future pull requests and make sure that most cases are covered and therefor less bugs will be introduced.

Currently my list of tests to make is the following:

### Login
- [x] Check that the login page shows correctly, with the correct messages and such
- [x] Check that the login fails when using bad credentials and ensure that a error message is shown
- [x] Check that correct credentials login the user

### Dashboard
- [x] Test showing the correct dimmer data, such as amount of posts, pages and users.
- [x] Test showing correct version number in the footer #2586

### Widgets
- [x] Test widget rendering #2588
- [x] Test that widget configuration can be overwritten in view #2588

### Google Analytics
- [ ] Test viewing Google Analytics notice when not configured
- [ ] Test viewing Google Analytics error when miss configured
- [ ] Test viewing Google Analytics connect button when proper configured

### Alerts
- [x] Test alerts rendering #2585
- [x] Test adding alerts components #2585

### Roles
- [ ] Test roles have permissions
- [ ] Test using default role if no `role_id` defined for their user
- [ ] Test using default role if invalid `role_id` defined for their user

### Permissions
- [x] Test erroring when permission does not exists #2587
- [x] Test not having permission #2587
- [x] Test having permission #2587
- [ ] Test making custom permission
- [ ] Test making BREAD permission
- [ ] Test menu item hides when missing required permission

### Users
- [x] Test user can see own profile page
- [x] Test user can edit own name
- [x] Test user can edit own email
- [x] Test user can edit own password
- [x] Test user can edit own avatar

### Media
- [ ] Test opening media section
- [ ] Test adding media
- [ ] Test adding folder
- [ ] Test renaming media
- [ ] Test renaming folder
- [ ] Test opening folder
- [ ] Test moving file
- [ ] Test moving folder
- [ ] Test deleting file
- [ ] Test deleting folder
- [ ] Test uploading multiple media files at once

### Posts
- [ ] **TODO: make list of tests**

### Pages
- [ ] **TODO: make list of tests**

### Category
- [ ] **TODO: make list of tests**

### Setting
- [ ] Test adding/editing/deleting a text box setting
- [ ] Test adding/editing/deleting a text area setting
- [ ] Test adding/editing/deleting a rich textbox setting
- [ ] Test adding/editing/deleting a check box setting
- [ ] Test adding/editing/deleting a radio button setting
- [ ] Test adding/editing/deleting a select dropdown setting
- [ ] Test adding/editing/deleting a file setting
- [ ] Test adding/editing/deleting a image setting

### Menu
- [ ] Test adding menu
- [ ] Test deleting menu
- [ ] Test editing menu
- [ ] Test adding menu item
- [ ] Test editing menu item
- [ ] Test deleting menu item
- [ ] Test moving menu item
- [ ] Test moving menu item to parent
- [ ] Test rendering menu
- [ ] Test rendering menu with custom view

### Database
- [ ] **TODO: make list of tests**

### Translations
- [x] Test if model is translatable
- [x] Test if model is not translatable
- [x] Test getting models translatable attributes
- [x] Test translating collection stays a collection
- [x] Test getting translator model of non existing translation
- [x] test getting translator model of existing translation
- [x] test saving non existing translator model
- [x] test saving existing translator model
- [x] test getting translation metadata from translator
- [x] test creating new translation
- [x] test updating translation

### Events
- [x] Test all events: #2584

### Breadcrump
- [ ] **TODO: make list of tests**

### BREAD
- [ ] **TODO: make list of tests**

### BREAD Relations
- **BREAD Has One Relation**
- [ ] Test browse/read/add/edit/delete `$this->hasOne()` relation
- [ ] Test browse/read/add/edit/delete `$this->hasOne()` relation with custom label
- [ ] Test browse/read/add/edit/delete `$this->hasOne()` relation with linking
- [ ] Test setting a `$this->hasOne()` relation to null or empty
- **BREAD Belongs To Relation**
- [ ] Test browse/read/add/edit/delete `$this->belongsTo()` relation
- [ ] Test browse/read/add/edit/delete `$this->belongsTo()` relation with custom label
- [ ] Test browse/read/add/edit/delete `$this->belongsTo()` relation with linking
- [ ] Test setting a `$this->belongsTo()` relation to null or empty
**BREAD Has Many Relation**
- [ ] Test browse/read/add/edit/delete single `$this->hasMany()` relation
- [ ] Test browse/read/add/edit/delete single `$this->hasMany()` relation with custom label
- [ ] Test browse/read/add/edit/delete single `$this->hasMany()` relation with linking
- [ ] Test browse/read/add/edit/delete multiple `$this->hasMany()` relation
- [ ] Test browse/read/add/edit/delete multiple `$this->hasMany()` relation with custom label
- [ ] Test browse/read/add/edit/delete multiple `$this->hasMany()` relation with linking
- [ ] Test setting a `$this->hasMany()` relation to null or empty
**BREAD Belongs To Many Relation**
- [ ] Test browse/read/add/edit/delete single `$this->belongsToMany()` relation
- [ ] Test browse/read/add/edit/delete single `$this->belongsToMany()` relation with custom label
- [ ] Test browse/read/add/edit/delete single `$this->belongsToMany()` relation with linking
- [ ] Test browse/read/add/edit/delete multiple `$this->belongsToMany()` relation
- [ ] Test browse/read/add/edit/delete multiple `$this->belongsToMany()` relation with custom label
- [ ] Test browse/read/add/edit/delete multiple `$this->belongsToMany()` relation with linking
- [ ] Test setting a `$this->belongsToMany()` relation to null or empty
**BREAD Has Many Through Relation**
- [ ] Test browse/read/add/edit/delete single `$this->hasManyThrough()` relation
- [ ] Test browse/read/add/edit/delete single `$this->hasManyThrough()` relation with custom label
- [ ] Test browse/read/add/edit/delete single `$this->hasManyThrough()` relation with linking
- [ ] Test browse/read/add/edit/delete multiple `$this->hasManyThrough()` relation
- [ ] Test browse/read/add/edit/delete multiple `$this->hasManyThrough()` relation with custom label
- [ ] Test browse/read/add/edit/delete multiple `$this->hasManyThrough()` relation with linking
- [ ] Test setting a `$this->hasManyThrough()` relation to null or empty
**BREAD Morph Many Relation**
- [ ] *Currently I have no clue how this works...*
**BREAD Morph To Many Relation**
- [ ] *Currently I have no clue how this works...*
**BREAD Morphed By Many Relation**
- [ ] *Currently I have no clue how this works...*

## Dusk Tests

- [ ] Make list of things to test using Dusk
- [ ] Make support for testing layout changes

## General

- [ ] Run all tests with other drivers than `sqlite`

Please come with your ideas for tests that should be added in case to gather a better level of stabilty.

**Comment by fletch3555** [comment]
This is (or at least should be) our #1 focus for the next release.

**Comment by marktopper** [comment]
Just started on something #1320

**Comment by lancepioch** [comment]
Labels: in progress, refactor, help wanted

**Comment by fletch3555** [comment]
@hojgr, I know it's been a while, but if you have a few minutes, can you review your changes in #2214 and check off any tests here that you may have completed?

Thanks!

**Comment by marktopper** [comment]
I have updated the list of completed tests from all the existing tests and from current pull requests.

**Comment by gavinkalika** [comment]
Do you guys have a dockerize app?

**Comment by fletch3555** [comment]
@gavinkalika, can you clarify your question? Specifically, I'm curious how it's relevant to this issue.

**Comment by tnylea** [comment]
Cleaning up old tickets. This is a great list of tests to add. I'm adding this to the v2.0 planning project to be implemented: https://github.com/the-control-group/voyager/projects/6
